---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgAwYMaAFRxZp6yB19LbpVVMmBGM+3D1HBV6OR8mKxUZEZFHYrZRlbe/+Qt1gOxNlSnsRqVfJnsMGJzUWzJqTZPrfgtgHWtGFLOdAhJ11JDm9dvnrFWSMYgYMJgnCd7CTVy6ylkP2ZT0c7NV+AixSixDGc5fHZvipzAE5BS6bjLvQPBjYCxNM+t4ANSgm1gMu7TbgkQqBlezQX36RmCj1jeg+MnRMpLT5bF5mOcpwsvJJsEb9mxJ/7sOdE1Rqk89LsFxw/bx+woF1sZgNWqbWGEiStquVWcLhNqux+E4QLrvdfOpurH8tMOgBeGvAGUru5ud8xP0fd0oC6TLFgDRnTsSSF0yfUrCnIoahL6vXK5cq3sB7iRZY92HeGaBT3J7YhJF00S0zKx2or0GF7hjJaKdDh7cmdG44iPwI3U66D6O29iToT5ZTVPZcJo6chP12X4/5LdW6lYtjUnFM1CPW5E/r+dsY+Z4cYfPNXSi9nidRvKRSnz8FkkoyZ64CwX56lP1tP3XXbX1ncoMPBAkz1XbLM2ICbGCzK9D4J6trXXEMvt84zlrN4hTiKSs5s1srwxXymyVus8bhUT1CAUH/GkifTTF5COaETgyQiIhSFFtDTSSvwzyX2K72fUjIsygWjSQU0f+yOBqPJOdveplBMUw687rN6KgJ+z0QEIRDW/55smfPXsH3v2tgVJccId8c69bGt6taikSaUXEmht9JTURaGNOfA==
    admin-user: AgC0Z+1H4gMRuGqlXaRkRKJsF/K3P604yrPNq7w+onjIV8tok+c2xLEyUXDLKb/pEgt3mqT0NJ1C78OLYLoy9+hNcPeffWVy9NaLSly5DIgwmKZyfVbQHfWwAI+eEAAE5Vz7vo1Rhp7n3iE4hpqUZYeXyVbfstA8/8ySqSmV+YHKQaaCPCrDte4RX+1ldQEl7PvaIYtmvPJqbzKYKOwgMcKuEDGQf4MnUwDjI09E3B2VjBR1Slrlj8wD64rfRDw8+kOD2ZNAuf5tf6gmwzXQzOgsIure8T4Vu6uqmUBDnI1r/ZnejWG8th0PxTMfS8jWAIIB0BkgnkuCu0gsjIBbBLned8gAys6EtlNZpvvuH+vQT781LhQ65rdk5W++efqNCfe0JgaNDABk2BRWnr8LuwFxId6yDlwqWnIwTjMMTnpAbDmsp51Ms5+ZXKR0YGvKvkTH2ZklT18SF333+6TVc9Lgvy9XnUUhKSGOX6W24QHTp09AQ26RCd/IBiggXCJQFOZ/wTljq2hMFtBnpyQMjsY9PuvcdTzh0CXiWoeIx40QstRwWo3eX9lF5aD8WvXEVoDoWU+SiPkeJkAW0+QHNK6EsM1ySvWHCBFCfsMgYPwz5NJ2nDp89kPQa3T6rgfZTwvjR3z7z+ZmD5z+klZfMZ5bZnDXJbJqVS7mldWb+BeQeoFqz1ovC7mr0Ft8ZFWYLEwZff6mbA==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
