---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBBiK1Uwu50rDk1VcYRnGQZogxOvlPOQJzfOm6tmaUrqPpqx76I7CR8DjdZYHv+NeRSVfJUm++/iNbp6lSkp0mHsvhd4Q+ewvOXRUZacd6Nhzr5Z1PQvo+0Q8ZN0mydHGGMmfAYHLyuWlX11JrAJAhcKaTiJMHbaNkDR1o0wxAHPjGL/fgwNsBvQJQXAqnU32siFnEzllWoPXZQaftJLiIdlGOEbZF1MXs83Na82zm7leYdQFeuPdDZySGiERIvLpUxedxd7DQdhLz73TkqoSNphzJbcsxyo/XOgkddQEjtyVw/rolvmPvcHqg5nR3OXvGSuFki8juoaZnZqecu/RH+7sDzFYDrMZhGJAhvVzk4e/M62/+uDYeK/8w0w7oCFx6iVAmh/Fih13Opajfz5Gn0QTtVwp01llGli9byqz66COqWjkXrBjD0dcIMKfBpHVY/gSPRq7z6f2W3MXAPFBavba3EZi1NMx5SIaOoumE9z7bc6gPNzTVvUp1aVxLboQcvDaex838jIJNhMXYVYAvyPjoTiCMYNpuFTojqBDy1UE52LAZb91Px/rgyxNxRSZiY7GrmW7eVjVnpRAA3+mcw8jhRVZ9eRDy3UE+ax/qoMd0h2EVXGFWjntI964KPd03x0JOpieh78gFAokv4lOtiTiMfL2IvbdFEy5nI15T/WXhh6UXhMIs5QqSWp7MiTjMhyYG0Gg0NYNnfCGgoqbGvnWc3JQ==
    admin-user: AgAyxfQwCFzSYpr38IgUynB2KqsYU0QBmLGb7XXMdEJjVEWpzoQjR+ayI9WG/DphpCz0cYpnCqaf1TRoIV9XIpZXKLHAxO4dOe9gPC8oDXLY0UOUhOk5d6HHX90LjSeocGgIUIsH0FEZVtSos2dejZToclVpqln3PV15vJgyR3ZbSYxPRXcAUgfrZ+7J31phc7ve2VdTSoF+H7e/v6IPwnBkumyzgK5Gm/A50TUrita575GirgN/Rtw39w15peTuWJFx+r7qK585xs3M567A8DKpxUd6E7j7xUbN/I40iNakwPZ6ZWfDFSTbQikkGbwgr7ejzJx/fGgGC10eeuRP3j35dceibW/4+951U0UP7A+KM5EkR7TJcIQjzr+/MoHDaCHOHnBQAPdoxItVNfrHrL/j1fvpwdCd14x+o9M1zGGbsUyCh3AdWVEDKr3e+TfLFNdVXi7ZXXCOTSc7MqdR7AlyLOfZskqDLaOQQyyYCqH5uO9ZlXIi1SKWiupeEo/iuce3aBTOPPsuKtdp+azhMe6E9V/uQWxHcWAiR53P49P2pHDJJoJsFlKv2QeXdUHFCxT73H2NGu+yJR6fJfieeONyq4XLnmdkEzEIP9Z2g8BAse6OScF2WuEtx5S8VKipKTtD5tpSccPPP/x9Ix9aCdv/21TnlGHb9ZNUizniU70+MMdek9PcttrK6o3pTHgfwiryshvzog==
  template:
    metadata:
      name: grafana-admin
      namespace: monitoring
    type: Opaque
